name: Python Application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add example text file
      run: |
        echo -e "Title\nThis is an example text file.\r\nAnother line, maybe?\r\nPerhaps, finally, some content, worth using as a dictation!" > input.txt

    - name: Run script with parameter
      run: |
        python dictation.py input.txt

    - name: Upload PPT as artifact
      uses: actions/upload-artifact@v4
      with:
          name: output-ppt
          path: output.pptx